id: TemplateDescription
name: Template Description
version: 1.0.0
description: <__trans phrase="_PLUGIN_DESCRIPTION">
author_name: Yamatsu
author_link: https://github.com/sorakakeru/mt-template-description
config_template: config.tmpl
l10n_class: TemplateDescription::L10N

schema_version: 1

object_types:
  template:
    td_description: text

callbacks:
  MT::App::CMS::template_param.edit_template:
    handler: $TemplateDescription::TemplateDescription::edit_template

  MT::App::CMS::template_source.template_table:
    handler: $TemplateDescription::TemplateDescription::template_source_template_table

  cms_pre_save.template:
    handler: $TemplateDescription::TemplateDescription::pre_save_template
